import 'package:untitled1/presentation/Modules/DeleteProduct.dart';
import 'package:untitled1/presentation/Modules/OrderDetails.dart';

const splashPath='/';
const introPath='/intro';
const signinPath='/signin';
const signwithphone='/signphone';
const signupPath='/signup';
const HomeScreenPath='/HomeScreen';
const OtbPhoneScreenPath ='/OtbPhoneScreenPath';
const MapScreenPath='/MapScreenPath';
const FavScreenPath='/FavScreenPath';
const OrderDetailsPath='/OrderDetailsPath';
const SettingScreenPath='/SettingScreenPath';
const AccontInfoPath='/AccontInfoPath';
const AddressInfoPath ='/AddressInfoPath';
const BMRScreenPath='/BMRScreenPath';
const ChangeEmailPath='/ChangeEmailPath';
const ChangePasswordPath='/ChangePasswordPath';
const MyOrdersPath='/MyOrdersPath';
const ShowPath='/ShowPath';
const DeleteProductScreenPath ='/DeleteProductScreenPath';