const splashPath='/';
const introPath='/intro';
const signinPath='/signin';
const signwithphone='/signphone';
const signupPath='/signup';
const HomeScreenPath='/HomeScreen';
const OtbPhoneScreenPath ='/OtbPhoneScreenPath';
const MapScreenPath='/MapScreenPath';
const SettingScreenPath='/SettingScreenPath';